#!/bin/sh
# Called by sxiv(1) after the external prefix key (C-x by default) is pressed.
# The next key combo is passed as its first argument. Passed via stdin are the
# images to act upon, one path per line: all marked images, if in thumbnail
# mode and at least one image has been marked, otherwise the current image.
# sxiv(1) blocks until this script terminates. It then checks which images
# have been modified and reloads them.

# The key combo argument has the following form: "[C-][M-][S-]KEY",
# where C/M/S indicate Ctrl/Meta(Alt)/Shift modifier states and KEY is the X
# keysym as listed in /usr/include/X11/keysymdef.h without the "XK_" prefix.

while read file 
do
	case "$1" in
	"w")  
		setbg "$file";;
	"b")  
		setbg "$file";;
	"d")	
		rm "$file" ;;
	"c")
                echo -n "$file" | xclip -selection clipboard ;;	
        "r")
                convert -rotate 90 "$file" "$file" ;;
	"n") 
		notify-send "$file";;

	"y") 
		cat "$file" | xclip -sel c -t $(file --mime-type -b "$file");;
	"i")	notify-send "$(mediainfo "$file")";;
	"space") path="$(readlink -f "$file")" ; lf -remote "send toggle '$path'" ;;

	esac
done
