#!/bin/sh

alias grub-update='sudo grub-mkconfig -o /boot/grub/grub.cfg'

#default flags
alias ls='ls --group-directories-first --color=auto'
alias ll='ls -hl'
alias la='ls -A'
alias lla='ll -A'
alias diff='diff --color=auto'
alias grep='grep --color'
alias egrep='egrep --color'
alias fgrep='fgrep --color'
alias ip='ip --color=auto'
alias bat='bat --theme=gruvbox-dark'
alias cat='bat -pp'
alias rsync='rsync --progress'
alias bc='bc -ql'

#shortened
alias vim='nvim'
alias p='sudo pacman'
alias pa='paru'
alias t='tmux'
alias sctl='sudo systemctl'
alias rcs='sudo rc-service'
alias rcu='sudo rc-update'
alias btctl='bluetoothctl'
alias lf='lfcd'
alias gtop='sudo intel_gpu_top'
alias enes='translate en-es'
alias esen='translate es-en'
alias ulog='uselog'

#shortcuts
alias nvimrc='nvim ~/.config/nvim/init.vim'
alias pdfconvert='libreoffice --convert-to pdf'
#alias yta='youtube-dl -f bestaudio --extract-audio --audio-format mp3 -o "%(title)s.%(ext)s"'
alias yta='yt-dlp -f "ba" --extract-audio --audio-format mp3 -o "%(title)s.%(ext)s"'
alias ytc='youtube-viewer --comments "$(xclip -sel c -o)"'
#alias yt='youtube-viewer'
alias horario='mdcat ~/Documents/UTN/2doAno/horarios.md'
alias alc='nvim ~/.config/alacritty/alacritty.yml'
alias nbu='nvim ~/.config/newsboat/urls'

#git
alias g='git'
alias gs='git status'
alias ga='git add'
alias gp='git push'
alias gbr='git branch'
alias gch='git checkout'
alias gc='git commit'
alias graph='git log --all --decorate --oneline --graph'
alias mpull='find . -mindepth 1 -maxdepth 1 -type d -print -exec git -C {} pull \;'

#clean home
alias units='units --history "$XDG_CACHE_HOME"/units_history'
alias mvn='mvn -gs "$XDG_CONFIG_HOME"/maven/settings.xml'
alias code='code --extensions-dir "$XDG_DATA_HOME/vscode"'
alias irssi='irssi --config="$XDG_CONFIG_HOME"/irssi/config --home="$XDG_DATA_HOME"/irssi'

alias mycli='mycli --myclirc ~/.config/myclirc'
alias qbittorrentui='qbittorrentui -c ~/.config/qbittorrent.ini'
