[general]
live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#282828"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#ebdbb2"
yellow = "#fabd2f"

[colors.cursor]
cursor = "#ff0000"
text = "CellBackground"

[colors.normal]
black = "#0c0c0c"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#a89984"
yellow = "#fabd2f"

[colors.primary]
background = "#0c0c0c"
bright_foreground = "#fbf1c7"
foreground = "#ebdbb2"

[colors.selection]
background = "CellForeground"
text = "CellBackground"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[font]
size = 8.0

[font.bold]
family = "DejaVu Sans Mono"
style = "Bold"

[font.bold_italic]
family = "DejaVu Sans Mono"
style = "Bold Oblique"

[font.italic]
family = "DejaVu Sans Mono"
style = "Oblique"

[font.normal]
family = "DejaVu Sans Mono"
style = "Book"

[[keyboard.bindings]]
action = "ScrollHalfPageUp"
key = "K"
mode = "~Alt"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollHalfPageDown"
key = "J"
mode = "~Alt"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "U"
mode = "~Alt"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "D"
mode = "~Alt"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "G"
mode = "~Alt"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "G"
mode = "~Alt"
mods = "Alt|Shift"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[[keyboard.bindings]]
command = "alacrittyopacit"
key = "A"
mods = "Alt|Shift"


[window]
opacity = 0.95

[window.padding]
x = 2
y = 5
